// <auto-generated />
namespace Angular2Mvc5Application3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m6));
        
        string IMigrationMetadata.Id
        {
            get { return "201607011108115_m6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
